name: ci/cd process

on:
  push:
    branches: 
      - 'main'

jobs:
  unit-test:
    name: unittest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: running unit test
      run: go test ./... -cover
  
  build-push-docker:
    name: build image and push docker hub
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: generate config file
        env:
          CONFIG: ${{secrets.APP_CONFIG}}
        run: |
          echo "$CONFIG" > ./app.config.json
      - name: build image
        run: docker build -t hanifbg/loginservice:1.0 .
      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: push docker registry
        run: docker push hanifbg/loginservice:1.0
  
  deployment-ec2:
    name: "Deploy to ec2 from registry docker hub"
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2 
      - name: configuration SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/alta-asia.pem
          chmod 400 ~/.ssh/alta-asia.pem
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/alta-asia.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'docker rm -f $(docker ps -a -q) || true && docker pull hanifbg/loginservice:1.0 && docker run -d -p 3000:3000 --name=loginservice hanifbg/loginservice:1.0'
